### PR TITLE
update atlantis configmap

### PR DESCRIPTION
**Pull request by wadexu007**

### CODE REVIEW

**Comment by wadexu007** [comment]
atlantis plan -p project-quick-demo -- -target=none.none

**Comment by wadexu007** [comment]
Ran Plan for project: `project-quick-demo` dir: `Terraform/quick_demo` workspace: `default`

<details><summary>Show Output</summary>

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the
│ result of this plan may not represent all of the changes requested by the
│ current configuration.
│ 
│ The -target option is not for routine use, and is provided only for
│ exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
╵

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p project-quick-demo`
* :put_litter_in_its_place: To **delete** this plan click [here](https://resource.project-44.cn/lock?id=wadexu007%252Flearning_by_doing%252FTerraform%252Fquick_demo%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p project-quick-demo -- -target=none.none`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by jessiezhang008 — APPROVED** [review]

**Comment by wadexu007** [comment]
atlantis apply

**Comment by wadexu007** [comment]
Ran Apply for project: `project-quick-demo` dir: `Terraform/quick_demo` workspace: `default`

<details><summary>Show Output</summary>

```diff
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes
│ requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other
│ changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is
│ provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
╵

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.


```
</details>

**Comment by wadexu007** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by wadexu007** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `Terraform/quick_demo` workspace: `default`

**Pull request merged**
