### PR TITLE
Atlantis github app config

### PR DESCRIPTION
**Pull request by wadexu007**

### CODE REVIEW

**Comment by wadexu007** [comment]
atlantis plan

**Comment by wadexu007** [comment]
atlantis plan

**Comment by wadexu007** [comment]
atlantis plan -p project-module-demo -- target=none.none

**Comment by wadexu007** [comment]
atlantis plan -p project-module-demo -- -target=none.none

**Review by jessiezhang008 — APPROVED** [review]

**Comment by jessiezhang008** [comment]
atlantis apply

**Pull request merged**
